# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://werkbaar.net
baseurl:
title: "WerkBaAr: Pittig trefpunt voor ondernemend talent"
email: aline@werkbaar.net
author: aline
description: WerkBaAr coacht ondernemende talenten & giet hun professionele ontdekkingstocht in een zinvol verhaal.
port: 4000

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:
  - title: github
    url:
  - title: linkedin
    url:
